language: node_js

node_js:
  - stable

sudo: false

install:
- npm install

script:
- cp .api/errors.json .vuepress/public/assets/errors.json
#- vuepress check-md

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: gh-pages
  keep-history: true
  committer-from-gh: true
  on:
    branch: master