language: node_js

node_js:
  - stable

sudo: false

install:
- npm install

#script:
#- vuepress check-md

before_deploy:
- npm run build
- cp CNAME .vuepress/dist/CNAME
- cp -ap redirects/. .vuepress/dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  keep-history: true
  name: openEO CI
  email: openeo.ci@uni-muenster.de
  on:
    branch: master