language: node_js

node_js:
  - stable

sudo: false

install:
- npm install

#script:
#- vuepress check-md

before_deploy:
- npm run build
- cp CNAME .vuepress/dist/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  keep-history: true
  committer-from-gh: true
  on:
    branch: master